---
kind: pipeline
name: compliance
type: docker

steps:
    -   name: composer
        image: thecodingmachine/php:8.4-v5-cli
        pull: always
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            COMPOSER_NO_INTERACTION: 1
        commands:
            - git config --global --add safe.directory $DRONE_WORKSPACE
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --prefer-dist
        depends_on: [ clone ]
    -   name: pnpm
        image: node:22-alpine
        pull: always
        commands:
            - corepack enable
            - pnpm install
        depends_on: [ clone ]
    -   name: stylelint
        image: node:22-alpine
        commands:
            - corepack pnpm lint:stylelint
        depends_on: [ pnpm ]
    -   name: eslint
        image: node:22-alpine
        commands:
            - corepack pnpm lint:eslint
        depends_on: [ pnpm ]
    -   name: prettier
        image: node:22-alpine
        commands:
            - corepack pnpm lint:prettier
        depends_on: [ pnpm ]
    -   name: phplint
        image: thecodingmachine/php:8.4-v5-cli
        environment:
            PHP_INI_ERROR_REPORTING: E_ALL & ~(E_NOTICE | E_WARNING | E_DEPRECATED)
        commands:
            - composer phplint
        depends_on: [ composer ]
    -   name: phpcs
        image: thecodingmachine/php:8.4-v5-cli
        environment:
            PHP_INI_ERROR_REPORTING: E_ALL & ~(E_NOTICE | E_WARNING | E_DEPRECATED)
        commands:
            - composer phpcs
        depends_on: [ composer ]
    -   name: phpstan
        image: thecodingmachine/php:8.4-v5-cli
        commands:
            - composer phpstan
        depends_on: [ composer ]

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: composer
        image: thecodingmachine/php:8.4-v5-cli
        pull: always
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            COMPOSER_NO_INTERACTION: 1
        commands:
            - git config --global --add safe.directory $DRONE_WORKSPACE
            - composer validate --ansi --no-check-all --no-check-publish
            - sudo composer install --no-progress --ansi --prefer-dist
        depends_on: [ clone ]
    -   name: pnpm
        image: node:22-alpine
        pull: always
        environment:
            NODE_ENV: production
        commands:
            - corepack enable
            - pnpm install --prod
        depends_on: [ clone ]
    -   name: phpunit
        image: thecodingmachine/php:8.4-v5-cli
        commands:
            - composer phpunit
        depends_on: [ composer ]
    -   name: webpack
        image: node:22-alpine
        environment:
            NODE_ENV: production
        commands:
            - corepack pnpm webpack --color
        depends_on: [ pnpm ]

trigger:
    ref:
        - refs/heads/master
        - refs/pull/**
        - refs/tags/**