openapi: 3.0.3
info:
    title: Status
    description: Simple status page
    version: 2.0.0
servers:
    -   url: 'https://status.animebytes.local:6443'
        description: Vagrant
paths:
    /api/status:
        get:
            tags:
                - status
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                allOf:
                                    -   $ref: "#/components/schemas/HttpResponse"
                                    -   type: object
                                        properties:
                                            status:
                                                type: object
                                                properties:
                                                    site:
                                                        type: object
                                                        properties:
                                                            status:
                                                                $ref: "#/components/schemas/Status"
                                                    tracker:
                                                        type: object
                                                        properties:
                                                            status:
                                                                $ref: "#/components/schemas/Status"
                                                            details:
                                                                type: array
                                                                items:
                                                                    type: object
                                                                    properties:
                                                                        status:
                                                                            $ref: "#/components/schemas/Status"
                                                                        alias:
                                                                            type: string
                                                                            description: Name of this tracker node
                                                    irc:
                                                        type: object
                                                        properties:
                                                            status:
                                                                $ref: "#/components/schemas/Status"
                                                    mei:
                                                        type: object
                                                        properties:
                                                            status:
                                                                $ref: "#/components/schemas/Status"
                                example:
                                    success: true
                                    status:
                                        site: 1
                                        tracker:
                                            status: 1
                                            details:
                                                -   alias: "rin"
                                                    status: 1
                                        irc: 1
                                        mei: 1
components:
    schemas:
        Status:
            type: integer
            enum: [ 0, 1, 2, 3 ]
            description: >
                Status of this element:
                  * `0` - down
                  * `1` - up
                  * `2` - issues
                  * `3` - maintenance
        HttpResponse:
            type: object
            properties:
                success:
                    type: boolean
                    description: Whether action was succesful
                error:
                    type: string
                    description: Message describing error cause
            required:
                - success
