name: testing

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

env:
    PHP_VERSION: 8.4
    PHP_EXTENSIONS: apcu, xml, curl, mbstring

jobs:
    backend:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Prepare environment
                id: ext-cache
                uses: shivammathur/cache-extensions@4595bea7d6630821b0a3a4894f816402faaf324c # v1
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    key: cache-v1
            -   name: Cache extensions
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.ext-cache.outputs.dir }}
                    key: ${{ steps.ext-cache.outputs.key }}
                    restore-keys: ${{ steps.ext-cache.outputs.key }}
            -   name: Set up PHP
                uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    tools: composer
                    coverage: none
                env:
                    fail-fast: true
            -   name: Get composer cache directory
                id: deps-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache dependencies
                uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
                with:
                    path: ${{ steps.deps-cache.outputs.dir }}
                    key: ${{ runner.os }}-${{ runner.arch }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-${{ runner.arch }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --ansi --prefer-dist
            -   name: PHPUnit
                run: composer phpunit
    frontend:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Set up PNPM package manager
                uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
            -   name: Set up NodeJS
                uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
                with:
                    node-version: 22
                    cache: pnpm
            -   name: Install dependencies
                run: pnpm install --prod
            -   name: Generate assets
                run: pnpm webpack --color